version: '3'

services:
  api:
    container_name: api
    build: 
      context: .
    ports:
      - 8000:8000
    expose: 
      - '8000'
    depends_on:
      - database

  database:
    container_name: database
    image: mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
    - '3306:3306'
