# Generated by Django 4.1.3 on 2022-11-28 14:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("imovel_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anuncio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plataforma", models.CharField(max_length=30)),
                (
                    "taxa_plataforma",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "criacao",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "atualizacao",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "imovel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="imovel_app.imovel",
                    ),
                ),
            ],
        ),
    ]
