# Generated by Django 4.1.3 on 2022-11-28 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Imovel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("limite_de_hospedes", models.PositiveIntegerField(default=0)),
                ("banheiros", models.PositiveIntegerField()),
                ("pet_friendly", models.BooleanField()),
                ("limpeza", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "data_ativacao",
                    models.DateField(
                        blank=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "criacao",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "atualizacao",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
