# Generated by Django 4.1.3 on 2022-11-28 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("anuncios_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "codigo_reserva",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("preco_total", models.DecimalField(decimal_places=2, max_digits=6)),
                ("comentario", models.CharField(max_length=256)),
                ("qtd_hospedes", models.PositiveIntegerField()),
                (
                    "criacao",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "atualizacao",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "anuncio_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anuncios_app.anuncio",
                    ),
                ),
            ],
        ),
    ]
